//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoWarehouse.DateBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public int Id { get; set; }
        public string NameItem { get; set; }
        public int CategoryItem { get; set; }
        public Nullable<int> PictureItem { get; set; }
        public Nullable<System.DateTime> TimeOfReceipt { get; set; }
        public string Quantity { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Picture Picture { get; set; }
    }
}
