//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoWarehouse.DateBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderEquipment
    {
        public int Id { get; set; }
        public int Worker { get; set; }
        public string Equipment { get; set; }
        public int Category { get; set; }
        public string Quantity { get; set; }
    
        public virtual Category Category1 { get; set; }
        public virtual User User { get; set; }
    }
}
